name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'
        cache: 'maven'
    
    - name: Install Google Java Format
      run: |
        curl -LJO https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar
        echo "java -jar google-java-format-1.17.0-all-deps.jar --replace \$(find . -name '*.java')" > format.sh
        chmod +x format.sh
    
    - name: Run Google Java Format
      run: ./format.sh
    
    - name: Build with Maven
      run: mvn -B clean package
    
    - name: Run Tests
      run: mvn test
